# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Local Development Chain
chain = "dev"
# Parity continously syncs the chain
mode = "active"
# Blockchain and settings will be stored in ~/.local/share/io.parity.ethereum.
base_path = "~/.local/share/io.parity.ethereum"

[rpc]
# Allows Cross-Origin Requests from domain 'all'.
cors = ["all"]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"

[websockets]
#  JSON-RPC will be listening for connections on IP all.
hosts = ["all"]
interface = "all"